MiniProject/Models/CharactersCreateVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiniProject.Models
{
    public class CharactersCreateVM
    {
        public string Name { get; set; }
        public string Backstory { get; set; }
        public SelectListItem[] TypeItems { get; set; }
        public int SpecialTrait { get; set; }   //Vilken datatyp för radio buttons?
    }
}

MiniProject/Models/CharactersIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiniProject.Models
{
    public class CharactersIndexVM
    {
    }
}

MiniProject/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniProject.Models;

namespace MiniProject.Controllers
{
    public class CharactersController : Controller
    {

        [Route("")]
        [Route("/characters/index")]
        public IActionResult Index()
        {
            return Content("Tjeeena");
            //return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CharactersCreateVM viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            return RedirectToAction(nameof(Index));
        }
    }
}

MiniProject/Views/Characters/Create.cshtml
@using MiniProject.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model MiniProject.Models.CharactersCreateVM

@{
    ViewBag.Title = "Create Character";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    <title>Create</title>
</head>
<body>
    <h2></h2>
    <form asp-action="Create" asp-controller="Characters">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>

        <label asp-for="Backstory"></label>
        <input asp-for="Backstory" />
        <span asp-validation-for="Backstory"></span>

        <label asp-for="SpecialTrait"></label>
        <input asp-for="SpecialTrait" />
        <span asp-validation-for="SpecialTrait"></span>

        <br/>

        <input type="submit" value="Create" />
    </form>


    @section scripts
        {
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
    }
</body>
</html>